# Generated by Django 5.1 on 2024-11-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='therapyscale',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
