# Generated by Django 5.1 on 2024-11-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_therapy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='malevoice',
            field=models.BooleanField(default=False),
        ),
    ]
